### ISSUE TITLE
F-Droid Veröffentlichung

### ISSUE THREAD

**Issue by Clevero** [johan12345/vertretungsplan#2]
gibt es eine möglichkeit, dass du App auf FOSS Andoir Appstore F-Droid (https://f-droid.org/) veröffentlichst?

damit würde man einerseits den pool der opensource apps dort im store erweiteren und hätte dadurch vielleicht auch neue nutzer? ich habe zum beispiel keinen google play store am laufen. alles läuft über f-droid oder notgedrungen mit aptoide. damit hätten nutzer, die dieselben richtlinien auf ihrem smartphone haben die möglichkeit die app zu installieren und auch informiert zu werden, wenn es updates gibt

**Comment by johan12345** [comment]
Grundsätzlich finde ich die Idee von F-Droid gut (auch wenn ich es selbst kaum nutze), aber um die App dort zu veröffentlichen, müsste ich die Abhängigkeit von den Google Play Services entfernen: Erstens, weil sie nicht Open Source sind, F-Droid das also nicht akzeptieren würde und zweitens, weil die ja auf Android-Geräten ohne Play Store auch nicht verfügbar sind.
Die Google Play Services werden für zwei Dinge benutzt:
- Google Analytics (Unwichtig, könnte ich für F-Droid auch weglassen oder durch Piwik austauschen)
- Google Cloud Messaging (Wichtig, ansonsten funktionieren Push-Benachrichtigungen nicht und im Aktuellen Zustand der App auch keine passwortgeschützten Schulen, weil die GCM-ID als Schlüssel in der Datenbank auf dem Server benutzt wird).
Außerdem weiß ich nicht, inwiefern F-Droid es erlaubt, dass die App zum Abrufen des Vertretungsplans einen zusätzlichen Server benutzt. Der Code, der dort läuft, ist allerdings ebenfalls Open Source (https://github.com/johan12345/vertretungsplan-server).
